### ISSUE TITLE
Install process for RN 0.61.5 doesn't work

### ISSUE THREAD

**Issue by lucianomlima** [react-native-community/react-native-template-typescript#140]
# Bug report

## Summary

When run `npx react-native init Example --template react-native-template-typescript@6.3.16 --version 0.61.5`
give the following error:

```
info Setting up new React Native app in /Users/luciano/projects/repos/Example
info Fetching template react-native-template-react-native-template-typescript@6.3.16...
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/luciano/projects/repos/Example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.4
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript@6.3.16...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript@6.3.16. This is not a critical error, you can work on your app.
(node:58103) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript@6.3.16
    at makeError (/Users/luciano/projects/repos/Example/node_modules/execa/index.js:174:9)
    at /Users/luciano/projects/repos/Example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createFromRemoteTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:115:5)
    at async createProjectFromTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:116:3)
    at async Object.initCompat (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:103:3)
(node:58103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:58103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Because npm is trying to fetch `react-native-template-react-native-template-typescript@6.3.16.` I try again with
`npx react-native init Example --template typescript@6.3.16 --version 0.61.5` but gives error too

```
[1/2] 🗑  Removing module react-native-template-typescript@6.3.16...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-typescript@6.3.16. This is not a critical error, you can work on your app.
(node:59083) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/luciano/projects/repos/Example/node_modules/react-native-template-typescript@6.3.16'
    at Object.lstatSync (fs.js:924:3)
    at walk (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/walk.js:38:22)
    at copyProjectTemplateAndReplace (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createProjectFromTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:116:3)
    at async Object.initCompat (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:103:3)
(node:59083) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:59083) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment info

There is no info output because it's not generate the project.

**Comment by lucianomlima** [comment]
Also... runs without RN version gives error too.
`npx react-native init Example --template react-native-template-typescript`

```
info Setting up new React Native app in /Users/luciano/projects/repos/Example
info Fetching template react-native-template-react-native-template-typescript...
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-template-react-native-template-typescript: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/luciano/projects/repos/Example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarn remove v1.22.4
[1/2] 🗑  Removing module react-native-template-react-native-template-typescript...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-react-native-template-typescript. This is not a critical error, you can work on your app.
(node:68029) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-react-native-template-typescript
    at makeError (/Users/luciano/projects/repos/Example/node_modules/execa/index.js:174:9)
    at /Users/luciano/projects/repos/Example/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createFromRemoteTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:115:5)
    at async createProjectFromTemplate (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:118:3)
    at async Object.initCompat (/Users/luciano/projects/repos/Example/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:68029) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:68029) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Maybe I need to do something?!

**Comment by lucianomlima** [comment]
I found it! Because I have old react-native cli installed globally, npx use the local version.
I need to pass `--ignore-existing` to works. Sorry 😅
