### ISSUE TITLE
Jest tests fail on a clean init project against RN 0.61.0-rc.2

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/react-native-template-typescript#68]
# Bug

Jest tests fail on a clean init project against RN 0.61.0-rc.2

output of yarn test
``` 
 ● Console

    console.error node_modules/react/cjs/react.development.js:172
      Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

  ● renders correctly

    Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14806:34
      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14809:13)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14830:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5154:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5211:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7353:28)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7780:5)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9162:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12981:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12955:22)

```

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 30.24 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 21, 23, 24, 25, 26, 27, 28
      Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 17.1.4828580
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.0-rc.2 => 0.61.0-rc.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Steps To Reproduce
```react-native init testrnnav --version 0.61.0-rc.2 --template typescript```
```yarn test```
```cd testrnnav/```
```yarn test```

**Comment by bartolkaruza** [comment]
Adding a ```jest.config.js``` file with the following content fixes this issue:

```
module.exports = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transformIgnorePatterns: ['node_modules/(?!(jest-)?react-native)'],
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
};
```

**Comment by radko93** [comment]
Hey, this is now working with 0.61.1 so I'm closing the issue.
